---
sudo: false
dist: xenial
language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --upgrade flake8

script:
  - flake8
  - pip install --upgrade ./
  - aws-acl-helper --help

notifications:
  email: false
